baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Kelstraud Technologies"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/blue_and_yellow_modern_cyber_security_job_training_program_linkedin_post__1_-removebg-preview.png"]